### ISSUE TITLE
Installed with .deb, command clarus-proxy throw only exceptions

### ISSUE THREAD

**Issue by Namirona** [clarus-proxy/proxy#15]
When clarus-proxy was installed  with .deb, lauching  : 
`clarus-proxy `
or 
`clarus-proxy -h`
throw exceptions. I think it's because of the config file but an helper should be nice

**Comment by dieriver** [comment]
Could you please paste the exception here? With this information we will be able to provide you further help

**Comment by Namirona** [comment]
Here is the error :
```
Exception in thread "main" org.xml.sax.SAXException: Fatal Error: URI=file:/home/ubuntu/ Line=1: Content is not allowed in prolog.
        at eu.clarussecure.proxy.spi.security.policy.MyErrorHandler.fatalError(MyErrorHandler.java:41)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:180)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
        at eu.clarussecure.proxy.spi.security.policy.SecurityPolicy.load(SecurityPolicy.java:47)
        at eu.clarussecure.proxy.Proxy.initialize(Proxy.java:61)
        at eu.clarussecure.proxy.Proxy.main(Proxy.java:213)

```

**Comment by dieriver** [comment]
It seems your security policy is malformed. Could you please transfer us the security policy you are using? (change the extension to txt to upload it here)

**Comment by Namirona** [comment]
OK, my bad. 
By default the config file is empty for the policy security contrary to the deployment with docker.

If I can advise, an helper and a check for the validity of the config file should be great.
Thanks

**Comment by dieriver** [comment]
I'm adding the the "enhancement" tag to this issue and assigning it to the person responsable for the docker integration
